#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Supporting Projects
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Supporting Projects
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/wip/wip-projects.org
:Created:  2018-03-24T20:05@Prek Leap (11.642600N-104.919210W)
:ID:       12e378c6-1005-4996-b52d-d5df698631e5
:VER:      575168811.071942621
:GEO:      48P-491193-1287029-15
:BXID:     proj:PPN5-7065
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Supporting Projects

In addition to published works, a series of projects will be
started that will test and explore many of the ideas in the
real world that are at the heart of the work.  Each project
is designed to be of practical use and help materially
improve people's life's today and their children, as well as
developing patterns, grammars and keystone designs that will
be included in the Works.

A few of the the initial projects that are in the planning
stages include:

  - Rethinking education as a lifelong process of learning, mastering
    and practicing existing and new skills.
  - An interdisciplinary research program focusing on the agricultural
    use of grass, from bamboo for construction, clothing and
    paper, to species of grasses used for ceral production,
    and others as forage for megafauna in natural and
    managed ecosystems.
  - Development of what we are calling, Slow AI.  Developing
    semi-autonomous machine-learning systems for monitoring
    and managing very slow long term (spanning years,
    decades and centuries) processes that are too slow for
    humans to manage.
  - Rethinking global-value chains that will leverage AI,
    robotic automation and distributed systems like
    blockchain technologies to shrink the atomic unit of
    global manufacturing and commerse from the ubiquitious
    40' Modal Shipping Container to a new unit that will be
    about the size of a shipping pallet.

All existing projects in the plannign stages will be
conducted in Cambodia and later, in Laos.


** Education

  - women have it tough in IT, and women in SE Asia have
    that plus a lot more on their plates.

  - remote work -- mostly for foreign companies
  - local jobs -- there is a dearth of qualified sysadmins
    here, and one reason that companies aren't adopting
    linux based technologies is the lack of qualified staff
    to manage it.

  - form shops where women can provide remote sysadmin and
    dev ops support -- good income, flexible hours and
    flexible workspace.

  - learn cognitive toolsets
    - rational thinking -- problem solving
    - learning how to learn
    - learning how to ask questions
    - learning how to research to solve problems
  - english communication skills
    - speaking -- business culture and tech culture
    - reading -- reading (Khmer or English) is not
      considered to be an imporant skill in Cambodia.
  - core math skills
    - algebra, calculus, algorithms
    - statistics 
  - linux operating system
  - programing
    - shell scripts
    - python, ruby, javascript
    - web stack, html, css, mysql, web frameworks

  - Invite professional women in IT from developed countries
    to act as mentors, and to help develop material for the
    course.
  - Get companies who are known as Remote work shops to take
    on students as interns (when they are ready).
  - Place students as much as a year before graduating, with
    the employer understanding that they will continue to
    study while they work
  - Alternately, will establish employee owned shops for
    groups of graduates to work together.
  - Outreach and education of local employers -- teach them
    about how open source can help their businesses, and get
    them to understand that flexible hours and remote
    workers are in their interest so long as they understand
    how to manage and do it correctly.
