#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Plan of the Work
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Plan of the Work
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/wip/wip-plan.org
:Created:  2018-03-22T21:18@Prek Leap (11.642600N-104.919210W)
:ID:       5777a09d-6a6d-4877-b2ac-16dd29024035
:VER:      575000375.224928262
:GEO:      48P-491193-1287029-15
:BXID:     proj:CIB5-5860
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

Chenla is a series of projects and published works to
demonstrate a way for Mankind to build advanced distributed
and stable technological civilization from first
principles. Chenla is not proposing the design of any
specific civilization, rather, the goal is to provide a
generative framework for the present and future generations
to make any number of civilizations.  The history of human
civilization is iterative and bottom up, building on the
civilizations that came before them.  With each iteration we
learn a little more, and do a little better.  It is hoped
that these works will be of use in making that process a
little less random, a little more focused, and a lot less
disruptive and destructive as it has all too often been in
the past.

** Works

The project began some fifteen years ago, with its roots
going more than 20 years before that.  Now that the final
structure is coming into focus, it is expected that
publication, starting with the first volume of the first
book /The Warp & Woof/ will go to press in 2020, with
subsequent volumes going to press every year or two after
that until completion.

The idea is that each work will provide the foundation
needed to create and understand the works that come after.

The principle works include:

*Warp & Woof*: 

An introduction to the concepts used in *A Pace-Layer Pattern
Language* and *A Primer*

*A Pace-Layer Pattern Language* (APPL):

APPL is meant to expand on the world in Christopher
Alexander's A Pattern Language (APL) which was published in 1977
cite:alexander:1977pattern

Where APL focused on towns, cities and the architecture of
builds, the scope of APPL will be to encompass as aspects of
civilization and human existence.

Another departure from APL will be that APPL will be what is
called a /literate program/ which combines text together
with computer software code.  The code is executed when the
pattern is generated.  This makes it possible for patterns
to be machine understandable.  This will be important in the
next work in the series, /The Primer/ which will is a a
group of /generative grammars/ which are expressed as both a
text narrative and code.

APPL will establish the broad patterns that can be used to
construct generative grammars that will be described in the
/Primer/.

*Primer*: 

The Primer is organized using two different models, the
/Pace-Layer/ model, and a /Succession-Stage/ model.

As in the previous two works, the Primer is not a
prescriptive design for civilization.  Rather it is meant to
create generate grammars that can be used to create very
long term civilizations from first principles that is
distributed and antifragile.

So rather than include plans and designs, it will include
standards, specifications and what we call /keystone
reference/ designs which can be used as archetypes that can
be adapted for a range specific needs of a ecological, economic,
technological, and cultural niches of any given civilization. 

*Hoard*

A hoard is a collection of treasured goods and information.
In Old English, the word for dictionary was a /worde hord/.

A Hoard is a collection of prescriptive and descriptive
knowledge used to build a specific civilization.  While our
Hoard might be used to build a civilization, it is expected
that it will be more useful as an example of how to apply
the APPL patterns and generative grammars to build civilization.

In many cases the only way to develop a keystone reference
design is by building a number of designs for specific
needs.  So in order for us to come up with many of the
patterns, generative grammars and keystone designs, we will
start with specific designs, identify what makes it work and
what can be used as a universal principle and then work
backwards.  The hoard will include all of this specific
design and development work that was done to develop
patterns and keystone designs.

*Arc*
  - archive
  - map
  - process


** The Warp & Woof


    - Ab initio
    - Points of View
    - Dualities
    - Structures
    - Generators
    - Boundries
    - Estrangement
    - Scaffolds
    - Principles
    - Patterns
    - The Way



** Supporting Projects

In addition to published works, a series of projects will be
started that will test and explore many of the ideas in the
real world that are at the heart of the work.  Each project
is designed to be of practical use and help materially
improve people's today, as well as developing patterns,
grammars and keystone designs that will be included in the
Works.

A few of the the initial projects that are in the planning
stages include:

  - Rethinking education as a lifelong process of learning, mastering
    and practicing existing and new skills.
  - An interdisciplinary research program focusing on the agricultural
    use of grass, from bamboo for construction, clothing and
    paper, to species of grasses used for ceral production,
    and others as forage for megafauna in natural and
    managed ecosystems.
  - Development of what we are calling, Slow AI.  Developing
    semi-autonomous machine-learning systems for monitoring
    and managing very slow long term (spanning years,
    decades and centuries) processes that are too slow for
    humans to manage.
  - Rethinking global-value chains that will leverage AI,
    robotic automation and distributed systems like
    blockchain technologies to shrink the atomic unit of
    global manufacturing and commerse from the ubiquitious
    40' Modal Shipping Container to a new unit that will be
    about the size of a shipping pallet.

All existing projects in the plannign stages will be
conducted in Cambodia and later, in Laos.


