#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Scale 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Scale
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/wip/warp/01-first/scale.org
  :Created:   2018-10-23T21:15@Prek Leap (11.642600N-104.919210W)
  :ID:        b6895ed9-5937-40b8-b2cc-3e33e97a7ff9
  :VER:       593576165.103732450
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:HGG5-2205
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

** Scope
** TL;DR


** Baseline

I take SCALE to be the primary measure of SPACE that Man can
comprehend and inhabit; both big and small and slow and
fast. 

It's the last great anthrocentrism we have yet to confront.

Copernicus nailed us to a spinning rock orbiting one of
billions of thermonuclear candles, which in turn orbits one
of billions of galaxies screaming away from each other in
all directions from an explosion that happened a meaningless
string of zeros ago.

Darwin reluctantly grounded us as just one of a score or
more species of Man who are related to every other living
creature that has ever lived or will ever live on this
planet, diverging from each other through speciation
governed by blind chance over staggering time scales.

The last bastion of exceptionalism has been mind, the
illusion of consciousness and our insistence of the ghost of
soul.

The problem with this of course is that human mind only
exists at human scales of time and space.  Increase the rate
of change too much and we stand frozen.  Slow things down,
and our tiny lifespans are little more than a firefly's
spark in the darkness.  Scale out in space and we are single
random cells in a rich biosphere teaming with life.  Zoom in
too close and we are little more than seas of nutrients
inhabited by as many microrganisms as their are stars in the
galaxy.  We as a species and as consciousness bearing selves
only exist in a tiny range of space-time in the middle
between the largest scale of the entire universe, and the
smallest quantum particles.  Stray too far outside human
scale and we might as well have never existed.

What is surprising is how much we have been able to learn
about the world at scales that we can not directly
experience.  Man has accomplished this through a process of
extension and externalization of memory, cognition and
muscle to observe and do things that are impossible
unaided.  This is our greatest strength but also our
greatest weakness because it has allowed us to see and act
at other scales, but only through proxies, and even then we
still treat these scales as if they were at our scale.  We
have tricks that give us the appearance that we can
understand things at other scales but in order for us to
comprehend they have to be translated to scales we can
understand.  Sometimes this works if imperfectly, but more
often than not, it doesn't. Given enough time, we might
eventually figure out how to think and act properly at such
scales but not now, not just yet.  The danger of course is
that what you don't know can and often will kill you.  So as
we blunder about doing things at scales we don't understand
we are putting ourselves in very real danger.

 


-----


Face this, that there is no independence of self from scale,
and we will be free...

Everything that Man has screwed up -- -- can be traced back
things done at wrong scales.  Our oversized neo-cortex made
us clever enough to avoid getting clobbered by negative feedback
mechanisms when we scaled larger than our design specs. Just
because you can do something make it a good idea.  Nature is
a giant nested Rube Goldberg machine made up of wonky
negative feedback loops.  You might dodge a few of the small
scale ones for a time, but for each feeback loop at
particular scale there is another bigger, nastier feedback
loop at the next scale up.  Eventually you'll hit a scale
that nothing in Felix's bag of tricks can fix.  The Earth's
planetary climate system is the first feedback system which
is beyond our ability to fix.


** Number


Stop for a moment and consider numbers -- the fingers on our
hands and feet come easy -- our neo-cortex extends that to
tens of ten and up until we are lost.  The chinese character
for 10,000 dipicts a myriad of insects, a swarm or cloud too
large to count, a magnitude impossible to comprehend even
though we know the world is made of innumerable magnitudes,
strings of zeros we can merely count.

Walk on any beach and what do you see?  A tawny stretch of
color bordered by lapping water on one side and whatever
passes for land on the other.  Bend down and scoop up a
fistful of sand.  It's still too much to see more than as an
amorphous shape. Drop the sand and look at your hand encased
in a thin layer of wet particles still too numerous as
anything but a course texture, a uniform gradiant with the
odd twinkle of quartz or ground glass for effect.  Wash your
hand in the surf then take the smallest pinch at your feet
and smooth it flat in your palm and you might, and even then
with some effort, see the individual grains at a scale your
brain can process.  The world is largely shore and forest,
not grains and trees. We understand the shore as one as we
understand a grain of sand as one. We can crudely connect
the two, that one is made up of inumerable instances of the
other, but the gulf between is so wide as to be largely
meaningless. Too much is lost in between.

When I was in grade school, the teachers had this clever
idea of a school-wide project to help students understand
how large a million of something was.  So all students were
tasked with collecting a million bottle caps. Bottle caps
began flowing into the school which were counted and added
to a number of enormous containers in the library.  The
piles of bottlecaps soon overflowed these containers and
became an amorphous mound of bags of bottlecaps that
threatened to swamp the entire library and we had only just
begun to cross the 150,000 mark.  And since most of the
bottlecaps had not been washed, the smell crossed the
threshold of being noticable to being quite unpleasant.  The
project was abandoned and it took more than a month to
dispose of the small mountain in the library. Clearly the
teachers themselves couldn't comprehend a million any more
than the children.


** 



By now you'd think we'd get the hint, that we are anything
but exceptional.  Old habits die hard, the exceptionalism of
mind, the illusion of consciousness, and the insistence of
the ghost of soul, persists.


----

The holarchy of Man -- exist as individual at one scale and
as a part at larger scales.  We exist at a scale that
encompasses both ourselves as individual wholes as well as
members of human scale groups that still retain a sense of
ourselves as both an individual whole and as part of a
collective whole -- but this doesn't scale -- scale to
groups larger than human scale -- much larger than dunbar's
number and we no longer exist as individuals, we loose our
humanity and sense of ourselves -- this is where bad things
begin to happen -- once you've moved up to scales we can't
comprehend and must resort to maps that strip us of
ourselves and our humanity.  We are designed to live in a
goldilocks petri-dish -- if we scale too much smaller, we're
just a skin-bag of water -- scale too much larger and we're
little more than a member of a herd, flock or swarm.  We no
longer exist as sentient creatures any more than an ant that
is unknowingly crushed by a pedestrian on her way to the
morning market.  This is not a metaphor or rhetorical device
-- we are literally no longer human at scales much smaller
or larger or faster and slower than the scale of the
petri-dish we are designed to inhabit.  The fact that we
have transgressed those scales means nothing because we have
had to resort to creating maps to understand even a small
fraction of what is happening beyond our human scale. We kid
ourselves that we understand, but these larger structures
are not directly comprehensible to us except at great effort
and only in hindsight.

** References


