#   -*- mode: org; fill-column: 60 -*-
#+STARTUP: showall
#+TITLE:   Eudaimon Contents
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/entity-TOC-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Eudaimon Contents
  :PROPERTIES:
  :CUSTOM_ID:
  :Name:      /home/deerpig/proj/chenla/wip/warp/02-eduaimon/index.org
  :Created:   2018-10-22T11:28@Prek Leap (11.642600N-104.919210W)
  :ID:        24cc33ef-6ed6-49db-9941-180665823997
  :VER:       593454603.538976012
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:MKW0-4268
  :Class:     primer
  :Entity:    toc
  :Status:    wip 
  :Licence:   MIT/CC BY-SA 4.0
  :END:

  - Contents
  - [[./abstract.org][Abstract]]
  - [[./intro.org][Introduction]]


  - Baseline

I take SCALE to be the central measure of SPACE that Man can
comprehend and inhabit; both big and small and slow and
fast. It's the last great anthro-centrism we have yet to
confront.  Face this, that there is no independence of self
from scale, and we will be free...

Stop for a moment and consider numbers -- the fingers on our
hands and feet come easy -- our neo-cortex extends that to
tens of ten and up until we are lost.  The chinese character
for 10,000 dipicts a myriad of insects, a swarm or cloud too
large to count, a magnitude impossible to comprend even
though we know the world is made of innumerable magnitudes,
strings of zeros we can merely count.

Walk on any beach and what do you see?  A tawny stretch of
color bordered by lapping water on one side and whatever
passes for land on the other.  Bend down and scoop up a
fistful of sand.  It's still too much to see more than as an
amorphous shape. Drop the sand and look at your hand encased
in a thin layer of wet particles still too numerous as
anything but a course texture, a uniform gradiant with the
odd twinkle of quartz or ground glass for effect.  Wash your
hand in the surf then take the smallest pinch at your feet
and smooth it flat in your palm and you might, and even then
with some effort, see the individual grains at a scale your
brain can process.  The world is largely shore and forest,
not grains and trees. We understand the shore as one as we
understand a grain of sand as one. We can crudely connect
the two, that one is made up of inumerable instances of the
other, but the gulf between is so wide as to be largely
meaningless. Too much is lost in between.

Copernicus nailed us to a spinning a rock orbiting a candle,
one of billions of thermonuclear furnaces in one of billions
of similar galaxys screaming away in all directions from an
explosion a meaningless string of zeros ago.  Darwin
relunctently grounded us as one of a score or more of
species belonging to a genus of sapiens (Man) that

By now you'd think we'd get the hint, that we are anything
by exceptional.  Old habits die hard, the exceptionalism of
mind, the illusion of consciousness, and the insistence of
the ghost of soul, persists.




    The holarchy of Man -- exist as individual at one scale and as a
    part at larger scales.  We exist at a scale that encompasses both
    ourselves as individual wholes as well as members of human scale
    groups that still retain a sense of ourselves as both an
    individual whole and as part of a collective whole -- but this
    doesn't scale -- scale to groups larger than human scale -- much
    larger than dunbar's number and we no longer exist as individuals,
    we loose our humanity and sense of ourselves -- this is where bad
    things begin to happen -- once you've moved up to scales we can't
    comprehend and must resort to maps that strip us of ourselves and
    our humanity.  We are designed to live in a goldilocks petri-dish
    -- if we scale too much smaller, we're just a skin-bag of water --
    scale too much larger and we're little more than a member of a
    herd, flock or swarm.  We no longer exist as sentient creatures
    any more than an ant that is unknowingly crushed by a pedestrian
    on her way to the morning market.  This is not a metaphor or
    rhetorical device -- we are literally no longer human at scales
    much smaller or larger or faster and slower than the scale of the
    petri-dish we are designed to inhabit.  The fact that we have
    transgressed those scales means nothing because we have had to
    resort to creating maps to understand even a small fraction of
    what is happening beyond our human scale. We kid ourselves that we
    understand, but these larger structures are not directly
    comprehensible to us except at great effort and only in hindsight.

    --> Maslow's Hierarchy of needs
        SEE: https://en.wikipedia.org/wiki/Maslow's_hierarchy_of_needs 

    - d-needs
    - c-needs (collective) 
    - freedom : boundries and trade-offs
    - obligations
    - rights
