#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Eudaimon Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Eudaimon Introduction
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/wip/warp/02-eduaimon/intro.org
  :Created:   2018-10-22T11:31@Prek Leap (11.642600N-104.919210W)
  :ID:        2b5c8dc9-684a-436c-9397-9f55fa6753af
  :VER:       593454732.286231287
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:YWS7-3820
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

    "Eudaimonia depends on all the things that would make
    us happy if we knew of their existence, but quite
    independently of whether we do know about them.
    — Wikipedia"

The Greeks tie eudaimon to virtues which are /states of the soul/ and
each Greek school of philosophy, the platonists, stoics and epicurians
quibble about how one goes about living a virtuous life.  This was
the original job of philosophy -- to make sense of how the world works
(which became natural philosophy) which became science, and how one
goes about living eudaimon (a good a virtuous life).

I don't want to weigh in on the how here so much as what are the
practical preconditions in terms Maslow's hierarchy that must be in
place in order for anyone to be able to think in terms of happiness
and virtue.  These constitute Maslow's d-needs (deficiency needs).

It should be noted that we will be only exploring secular humanistic
solutions which do not require a supernatural lawgiver.  This does not
mean that one excludes the other but there will always be a subset of
quirky divine laws that are throwbacks from a different age which are
left over and don't make any sense today which will be incompatible
with some religious legal frameworks, in particular dietary and dress
restrictions that can be can be observed by individuals who proscribed
to such belief systems but can not be universally imposed on others.

This will provide us with a baseline.

We can then go on to define what constitutes freedom in a
hyper-connected technological industrial civilization.  This gives us
the boundries and trade-offs that we must accept.

Finally we can briefly explore the range of obligations and rights of
persons living in such a society.  Many rights come with strings in
that they must be reciprocal and therefore limit the freedom of both
parties.  Freedom is directly proportionate to the size of its
audience -- this is largely because of edge cases, and the more edge
cases you need to specifically cater too the more restrictive things
get for the entire group.  It's also true that greater the need to
make exceptions for edge cases, the less tolerent the collective body
tends to be.  The Golden Rule works very well as is, unless someone in
the group believes that there are exceptions and that it doesn't apply
to everyone.  The more a community is fragmented the more rules are
needed to keep the peace between the different factions.





** References

Koltko-Rivera, M. E., Rediscovering the later version of maslow's
hierarchy of needs: self-transcendence and opportunities for theory,
research, and unification., Review of general psychology, 10(4), 302
(2006). cite:koltko:2006rediscovering

Heylighen, F., A cognitive-systemic reconstruction of maslow’s theory
of self-actualization, Behavioral Science, 37(1), 39–58 (1992).
http://dx.doi.org/10.1002/bs.3830370105 cite:heylighen:1992cognitive

Maslow, A. H., New Knowledge In Human Values (1959), : Harper & Brothers.
cite:maslow:1959human-values

Maslow, A. H., Toward a psychology of being (2013), : Start Publishing LLC.
cite:maslow:2013toward

Maslow, A. H., Religions, values, and peak-experiences (compass)
(1994), : Penguin (Non-Classics).  cite:maslow:1994religions

Maslow, A. H., The farther reaches of human nature (1993), : Penguin
(Non-Classics).  cite:maslow:1993farther

Maslow, A. H., A theory of human motivation., Psychological Review,
50(4), 370–396 (1943).  http://dx.doi.org/10.1037/h0054346
cite:maslow:1943human-motivation

Maslow, A. H., Motivation and personality (1987), : Harper.
cite:maslow:1987motivation
