#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Warp & Woof Abstract
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Warp & Woof Abstract
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/wip/warp/abstract.org
  :Created:   2018-10-25T09:53@Prek Leap (11.642600N-104.919210W)
  :ID:        cde306a0-71d1-4f25-8561-4eb6f047ef53
  :VER:       593708077.732857849
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:IQC2-8810
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

** Scope



** TL;DR

To talk of civilization is to step back so far from ourselves that
we as individuals no longer exist.  It is to see a forest in which
we are just another tree lost in the canopy.  Civilization is the
totality of a way of life that manifests itself as a process stack
with each layer representing a different rate of change and
abstraction.

   Civilization is not a built thing made from coin, brick, ego or
   other friable fare.  These things are side-effects that emerge from
   generative processes on the periphery of our awareness.  You can't
   design or plan a civilization any more than you can a tree.  You
   can prune, graft, transplant, stunt or kill it but it can only here
   it's own genetic perogrative to grow as best it can in the context
   it happens to be find itself in.  With great patience you might be
   able to train it to grow into a specific form, but invariably it
   will outlive you and its next caretaker or the one after that will
   tire of playing someone else's game.

   It is as much a physical as it is an concept, ideal and entrenched
   habit.  Civilization should be a verb.  We /practice/ civilization
   as much as we live within one.  Civilization is simply the
   accumulated practice, knowledge and made things that are part and
   parcel of cooperation. It can be thought of as a very slow mill,
   grinding down any king, tyrant, saint, savior or god that may hold
   sway for a lifetime or even a millennia, and reduced to grist. It's
   a lossy process, with events and people recorded as history, which
   is condensed into legand and eventually through weather and wear is
   worn down into myth.  Herodotus got that, that history was not what
   happened but what was /written/, and that a little is lost with
   each retelling.  

   Myth is often dismissed as a fiction -- but Herodotus knew better,
   and that you had to place accounts of what was written in context
   with what was believed to produce an approximation of truth.  Myth
   is all that remains of the past that still exists in the present.

   Civilization is not a made thing so much as the accumulation of all
   that falls on the threshing floor, collecting what has was torn
   loose admist the /sturm und drang/, the process of the present
   becoming something else.  As the character Hannibal Lector said,
   "and be grateful. Our scars have the power to remind us that the
   past was real."[fn:1]

   From here it's worth spending some time considering Vico, which, as
   the sources I cite indicate, I came to via Joyce back when I was in
   high school.  I mention this because coming to Vico via Joyce gets
   one tangled up with Bruno.  This is far from being a bad thing. But
   to untangle Bruno from Vico Bruno we must turn to Samuel Beckett
   who was once a close disciple of Joyce long before lapsing into the
   unspeakably obtuse terseness that is indelibly stamped on his
   mature work.  Beckett's essay "Dante... Bruno. Vico.. Joyce" is
   about how Joyce used Vico as a structural scaffold for /Finnegans
   Wake/ but it is, in the end Vico's thesis on the relationship
   between civilization, history and myth.


#+begin_quote
His division of the development of human society into three ages:
Theocratic, Heroic, Human (civilized), with a corresponding
classification of language Hieroglyphic (sacred), Metaphorical
(poetic), Philosophical (capable of abstraction and generalisation),
was by no means new, although it must have appeared so to his
contemporaries.  He derived this convenient classification from the
Eqyptions, via Herodotus.  At the same time it is impossible to deny
the originality with which he applied and developed its implications.
His exposition of the ineluctable circular progression of Society was
completely new, although the germ of it was contained in Giordano
Bruno's treatment of identified contraries.  But is in Book 2.,
described by himself as '/tutto il corpo... la chiave masetra... dell'
opera/', that appears the unqualified originality of his mind; here he
evolved a theory of the origins of poetry and language, the
significance of myth, and the nature of barbaric civilization that
must have appeared nothing less than an impertanant outrage against
tradition.... [pp.4-5]

It is first necessary to condense the thesis of Vico, the scientific
historian.  In the beginning was the thunder: the thunder set free
Religion, in its most objective and unphilosophical form — idolatrous
animism: Religion produced Society, and the first social men were the
cave-dwellers, taking refuge from a passionate Nature : this primitive
family life recieves its first impulse towards development from the
arrival of terrified vagabonds : admitted, they are the first slaves :
growing stronger, they exact agrarian concessions, and a despotism has
evolved into a primitive feudalism : the cave becomes a city, and the
feudal system a democaracy : then an anarchy : this is corrected by a
return to a monarchy : the last stage is a tendency towards
interdestruction : the nations are dispersed, the Phoenix of Society
arises out of their ashes.  To this six-termed social progression
corresponds a six-termed progression of human motives : necessity,
utility, convenience, pleasure, luxury, abuse of luxury : and their
incarnate manifestations : Polyphemus, Achilles, Caesar and Alexander,
Tiberius, Caligula and Nero.  At this point Vico applies Bruno —
though he takes very good care not to say so[fn:2] — and proceeds from
rather arbitrary data to philosophical abstraction.  There is no
difference, says Bruno between the smallest possible chord and the
smallest possible arc, no difference between the infinite circle and
the straight line. The maxima and minima of particular contraries are
one and indifferent.  Minimal heat equals minimal cold.  Consequently
transmutations are circular.  The principle (minimum) of cone contrary
takes its movement from the principle (maximum) of another.  Therefore
not only do minima coincide with the minima, the maxima with the
maxima, but the minima with the maxima in the succession of
transmutations.  Maximal speed is a state of rest.  The maximum of
corruption and the minimum of generation are identical : in principle,
corruption is generation.  And all things are ultimately identified
with God, the universal monad, Monad of monads.  From these
considerations Vico evolved a Science and Philosophy of History, It
may be an amusing exercise to take an historical figure, such as
Scipio, and label him No.3; it is of no ultimate importance.  What is
of ultimate importanance is the recognition that the passage from
Scipio to Caesar is as inevitable as the the passage from Caesar to
Tiberius since the flowers of corruption in Scipio and Caesar are the
seeds of vitality in Caesar and Tiberius.  Thus we have the spectacle
of a human progression that depends for its movement on individuals,
and which at the same time is independent of individuals in virtue of
what appears to be a preordained cyclicism.  It follows that History
is neither to be considered as a formlass structure, due exclusively
to the achievements of individual agents, nor as possessing reality
apart from and independent of them accomplished behind their backs in
spite of them, the work of some superior forcem variously known as
Fate, Chance, Fortune, God.  Both these viewsm the materialistic and
the transcendental, Vico rejects in favour of the rational.
Individuality is the concretion of universality, and every individual
action is at the same time superindividual.  The individual and the
universal cannot be considered as indistinct from each other. History
then, is not the result of Fate or Chance — in both cases the
individual would be separated from his product — but the result of a
Neccessity that is not Fate, of a Liberty that is not Chance (compare
Dante's 'yoke of liberty').  This force he called Divine Providence,
with his tongue, one feels, very much in his cheek.  And it is to this
Providence that we must trace the three institutions common to every
society : Church, Marriage, Burial.  this is not Boussuet's
Providence, transcendental and miraculous, but immanent and the stuff
of human life, working by natural means.  Humanity is its work in
itself.  God acts on her, but by means of her.  Humanity is divine,
but no man is divine.

— /Dante... Bruno. Vico.. Joyce/, Samuel Beckett (1929)
  cite:beckett:1929exagmination
#+end_quote


   Where Herodotus was the father of history, it was Vico who gave a
   philosophy of history.


#+begin_quote
Giambattista Vico (1668-1744) is the author of /Principi de Scienza
Nuova/ (The New Science), in which is expounded his theory that a
common cyclical pattern identifies the histories of diverse nations.
The cycle consists if (i) the age of gods, represented in primitive
society by the family life of the cave, to which God's thunder had
driven manl (ii) the age of heroes, characterized by the continual
revolutionary movements of the plebian against the patricians; (iii)
the age of people, the final consequence of the levelling influence of
revolutions. The three ages are typified by the institutions of birth,
marriage and burial, respectively, and followed by a short lacuna, the
/ricorso/ (resurrection) linking the third age to the first of a
subsequent cycle.

— Annotations to /Finnegans Wake/, Roland McHugh (1980)
  cite:mchugh:1980annotations 
#+end_quote







The bones of any civilization is reflected in the the word itself,
derived from the Latin *Civilis* "civil" and related to *Civis*
"citizen" and *Civitas* "city".

   Our ability to survive as individuals and as societies is directly
   proportionate to how well we cooperate with each other.
   Cooperation requires compromise and something more courtesy,
   respect, and politeness, terms that in today's world sound
   increasingly quaint which is a miner's canary warning us that the
   atmosphere is poisoned.

* Footnotes


[fn:1] /Red Dragon/, Brett Ratner (director), Thomas Harris (novel),
Ted Tally (Screenplay), Universal Pictures, 2002.  url:
https://www.imdb.com/title/tt0289765/?ref_=ttqt_qt_tt


[fn:2] James Joyce's Italian language teacher at University College,
Dublin was a Jesuit named Father Charles Ghezzi.  "Ghezzi piously
reminded Joyce that Bruno was a terrible heretic, and Joyce dryly
rejoined, 'Yes, and he was terriby burned." — Ellmann pp.59.  Joyce
later referred to the incident in /Portrait/ "Then went to
college. Other wrangle with little roundhead rogue’s eye Ghezzi. This
time about Bruno the Nolan. Began in Italian and ended in pidgin
English. He said Bruno was a terrible heretic. I said he was terribly
burned. He agreed to this with some sorrow."

* References

  - Beckett, S., Our exagmination round his factification for 
    incamination of work in progress (1972), : New Directions.
    cite:beckett:1929exagmination
  - Ellmann, R., James Joyce (1982), : Oxford University Press.
    cite:ellmann:1982james-joyce
  - Joyce, J., A portrait of the artist as a young man and dubliners
    (2004), : Barnes & Noble Books.  cite:james:2004portrait
  - McHugh, R., Annotations to finnegans wake (1980), : John Hopkins
    University Press.  cite:mchugh:1980annotations
  - Giambattista Vico; Translated by Thomas Goddard Bergin, M. H. F.,
    The new science of giambattista vico: translated from the third
    edition (1744) (1948), : Cornell University Press.
    cite:vico:1948new-science 
