#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Warp & Woof Abstract
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Warp & Woof Abstract
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/wip/warp/abstract.org
  :Created:   2018-10-25T09:53@Prek Leap (11.642600N-104.919210W)
  :ID:        cde306a0-71d1-4f25-8561-4eb6f047ef53
  :VER:       593708077.732857849
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:IQC2-8810
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

** Scope



** TL;DR



To talk of civilization is to step back so far from ourselves that we
no longer exist.  It is to see a forest in which we are just another
tree lost in the canopy.  Civilization is the totality of a way of
life that manifests itself as a protocol stack with each layer
representing a different rate of change and abstraction.

---

Civilization is not a built thing, made from coin, rock, ego or other
friable fare.  These are side-effects that emerge from generative
processes on the periphery of our awareness.  You can't design or plan
a civilization any more than you can a tree.  You can prune, graft,
transplant, stunt or kill it but it can only here it's own genetic
perogrative to grow as best it can in the context it happens to be
find itself in.  With great patience you might be able to train it to
grow into a specific form, but invariably it will outlive you and its
next caretaker or the one after that will tire of playing someone
else's game.

The bones of any civilization is reflected in the the word itself,
derived from the Latin /Civilis/ "civil" and related to /Civis/
"citizen" and /Civitas/ "city".  It is as much a physical as it is an
concept, ideal and entrenched habit.  It should be a verb -- we
/practice/ civilization as much as we live within one.  Civilization
is simply the accumulated practice, knowledge and made things that are
part and parcel of cooperation. It can be thought of as very slow
mill, grinding down any king, tyrant, saint, savior or god that may
hold sway for a lifetime or even a millennia, as little more than
grist.

Our ability to survive as individuals and as societies is directly
proportionate to how well we cooperate with each other.  Cooperation
requires compromise and something more courtesy, respect, and
politeness, terms that in today's world sound increasingly quaint
which is a miner's canary warning us that the atmosphere is poisoned.



